name: test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "luajit-openresty"
    - uses: leafo/gh-actions-luarocks@v4
    - run: luarocks install luacheck
    - run: luacheck lib

  test:
    runs-on: ubuntu-latest
    container:
      image: openresty/openresty:alpine-fat
      options: --init

    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: |
          luarocks install lua-resty-http 0.16.1-0
          luarocks install busted
      - run: ./bin/busted
